fix: Remove `transient-store` as it does not work with high concurrency tests
Running all tests on a multicore machine with btrfs filesystem makes the runner fail with the following error:

```
thread 'health::alive' (213601) panicked at nethsm/src/test.rs:155:21:
error: rustainers::runner::error::RunnerError - Fail to start container because Fail to execute command
podman run --detach --rm --publish 8443 --network=bridge docker.io/nitrokey/nethsm:3e45f2f3
------ stdout ------

------ stderr ------
Error: runc: runc create failed: unable to start container process: error during container init: exec: "/bin/sh": stat /bin/sh: no such file or directory: OCI runtime attempted to invoke a command that was not found

runner: Podman 5.6.2 - podman-compose 1.5.0
container: RunnableContainer {
```

It seems to be a known issue with podman and since the performance benefit from that option were not significant this patch removes it.

See: https://github.com/containers/podman/issues/19020
Signed-off-by: Wiktor Kwapisiewicz <wiktor@metacode.biz>